### ISSUE TITLE
interoperability with round-tripping through data format broken (x-issue)

### ISSUE THREAD

**Issue by adienes** [apache/arrow-julia#508]
due to recent release `InlineStrings@1.4.1`, possible `Arrow.jl` should pin to `1.4.0` until the problem is resolved upstream

https://github.com/JuliaStrings/InlineStrings.jl/issues/76

```
# julia

julia> Arrow.write("mwe.arrow", Tables.rowtable((; a = String3["xyz", "123"])))
```

```
# python

>>> import polars as pl
>>> pl.read_ipc("mwe.arrow")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/polars/utils/deprecation.py", line 133, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/utils/deprecation.py", line 133, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/io/ipc/functions.py", line 103, in read_ipc
    return pl.DataFrame._read_ipc(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/polars/dataframe/frame.py", line 990, in _read_ipc
    self._df = PyDataFrame.read_ipc(
               ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: cannot create series from Extension("JuliaLang.InlineStrings.InlineString3", Utf8, Some(""))
```

**Comment by quinnj** [comment]
This seems to be a polars issue
